### ISSUE TITLE
ImagePreview is not a constructor

### ISSUE THREAD

**Issue by martinko2009** [chemzqm/images-preview#1]
when I use webpack
I write like blew:

var ImagePreview = require("images-preview");
var imgs = document.querySelectorAll('.gallery img');
new ImagePreview(imgs);

browser will alert the error message:ImagePreview is not a constructor

**Comment by chemzqm** [comment]
It' written in es6, so the documentation is wrong, I've fixed that.

You could change require to `require("images-preview").default`

Thanks for reporting.
