### ISSUE TITLE
In the Ipad I tap one picture,the picture is not zoom in to fit the window

### ISSUE THREAD

**Issue by martinko2009** [chemzqm/images-preview#2]
when I show the pics in the page in the Ipad like belew
![image](https://cloud.githubusercontent.com/assets/3345987/21253591/e5faafba-c39a-11e6-80f5-cba9ed3fe313.png)

then, I tap one picture,the picture is not zoom in to self-fit with the window,just small picture.
![tap](https://cloud.githubusercontent.com/assets/3345987/21253636/1ba3ca20-c39b-11e6-883e-80a0bfa17570.jpg)

because these pictures‘ size is big enough

**Comment by chemzqm** [comment]
@martinko2009 应该是 convert 选项没有设置吧？你使用 chrome 移动模式调试也是这样吗？

**Comment by martinko2009** [comment]
预览的图片和缩略图的图片是同一个图片，缩略图的时候，只是把图片的长度和宽度设置小一些。

**Comment by martinko2009** [comment]
![image](https://cloud.githubusercontent.com/assets/3345987/21256297/6ef89bea-c3ac-11e6-9e22-1f27fcaf706e.png)
![image](https://cloud.githubusercontent.com/assets/3345987/21256303/7d20f6f4-c3ac-11e6-9000-e1ab08cdf5fa.png)

**Comment by martinko2009** [comment]
convert是没有设置，因为小图片和预览放大时候的图片链接是一致的，是同一张图片

**Comment by chemzqm** [comment]
刚才一直在重新安装包，已经定位到 bug 了

**Comment by chemzqm** [comment]
@martinko2009 有个参数错位了，新版 0.1.10 已修复

**Comment by martinko2009** [comment]
还有一个问题，就是在ipad的浏览器上看，有时候点击预览图片，第一张图片的时候，会有宽的黑边，图片的位置就往下沉了，后面几张是好的，但是一开始会有黑边，然后图片自动上升，有这样的一个调整过程。

**Comment by chemzqm** [comment]
@martinko2009 你用 ipad 试下这个网页 https://mobkits.github.io/images-preview/ 也有同样问题吗？

**Comment by martinko2009** [comment]
我又试了一下你发布的版本，我将原先的
```
var imgs = document.querySelectorAll('.gallery img');
	var aa = new ImagePreview(imgs,{
    convert:function(src){
        return src
    }
});
```
修改为如下：
```
var imgs = document.querySelectorAll('.gallery img');
	var aa = new ImagePreview(imgs);
```
貌似没有这个问题了。
但是我在想，是不是我上面的一个convert参数引起的呢，因为当小图片和放大后的图片是同一张的时候，使用了convert参数后，会导致这样的问题呢。

引申开的话，如果小图片和放大预览图片大小相差不大会不会导致这样的问题，或者相差很大，也会导致那个黑边的问题呢。

 另外你给我的那个链接我也在ipad上试过了，貌似没有这样的问题。:)

**Comment by chemzqm** [comment]
@martinko2009 不是你代码的问题，是上个版本代码有 bug，图片没有成功加载导致的，这跟图片大小是没有关系的，没你想的那么复杂。

**Comment by martinko2009** [comment]
我又尝试了一下，发现确实存在这个问题，当点击图片，图片正在转圈加载，图片没有完全加载完成的时候，这个时候滑动图片就会出现我上面说的问题，

比如：
点击小的缩略图，进行预览，这时图片正在加载，如下图：
![image](https://cloud.githubusercontent.com/assets/3345987/21381325/9c6e5aa0-c795-11e6-8703-ad8020c726da.png)
这个也是正在加载中的图片，插件会在页面中央有一个正在旋转的圆圈，提示正在加载：
![image](https://cloud.githubusercontent.com/assets/3345987/21381347/b5019c1c-c795-11e6-8e48-7ef8d38bf1f5.png)
这个时候我用手指滑动图片，等图片加载完成后，这个时候图片的上部出现了黑色的边框，这个黑色的边框的出现，我感觉是图片往下移动了的关系，如下图：
![image](https://cloud.githubusercontent.com/assets/3345987/21381369/d1a8575c-c795-11e6-8a2f-70600ec12d84.png)
但是滑动这张图片后，后面的图片就正常了，图片的上部就没有黑色边框了，如下图：
![image](https://cloud.githubusercontent.com/assets/3345987/21381397/03b76756-c796-11e6-8d21-17b470143def.png)

**Comment by chemzqm** [comment]
上下左右的黑框是故意加上去的

**Comment by martinko2009** [comment]
不是的，如果我加载完毕后，再滑动，图片是全屏的，没有黑边的呀
